// Generated by CoffeeScript 1.4.0
var CoffeeShopClient,
  _this = this;

this.app = new (CoffeeShopClient = (function() {

  function CoffeeShopClient() {}

  CoffeeShopClient.prototype.bootstrap = function(env, options) {
    this.ENV = env || 'production';
    options = options || {};
    this.debug = options.debug || this.ENV !== 'production';
    this.trace = options.trace || false;
    this.started = new Date();
    return this.log('app ready.');
  };

  CoffeeShopClient.prototype.log = function(o) {
    var current;
    if (this.debug && console) {
      current = new Date();
      console.log(typeof o === 'string' ? "[" + ((current - this.started) / 1000) + "s] " + o : o);
      if (this.trace) {
        return console.trace();
      }
    }
  };

  return CoffeeShopClient;

})());

this.__exported__ = {};

this.module = {};

this.require = function(file) {
  return _this.__exported__[file];
};

this.global = {
  exports: function(file, o) {
    return _this.__exported__[file] = o;
  }
};
