#!/usr/bin/env sh
# Process Loop
# Usage:
#
#   ./loop node --debug app.js
#
#   Ctrl+C Restarts
#   Ctrl+\ Quits
#

ctrl_c() {
  echo -en "\n\n*** Restarting ***\n\n"
}

ctrl_backslash() {
  echo -en "\n\n*** Killing ***\n\n"
  exit 0
}

# trap keyboard interrupt (control-c)
trap ctrl_c SIGINT
trap ctrl_backslash SIGQUIT

# the loop
reset; while true; do $*; done
