// Generated by CoffeeScript 1.4.0
var app, express;

process.env.ROOT = __dirname + '/static/';

process.env.development = true;

express = require('express');

app = express();

app.engine('html', function(path, options, cb) {
  return fs.readFile(path, 'utf8', function(err, str) {
    return cb(err, str);
  });
});

app.use(express["static"](process.env.ROOT + 'public/'));

require(process.env.ROOT + 'app/controllers/application')(app);

app.listen(3000);
